import Ajv from "ajv";
import type { JSONSchemaType } from "ajv";
import type { Component } from "./component";

interface Sketch {
  component: Record<string, Component>;
}

// Generated by
// $ npx typescript-json-schema --noExtraProps --required tsconfig.json Sketch
const sketchSchema: JSONSchemaType<Sketch> = {
  $schema: "http://json-schema.org/draft-07/schema#",
  additionalProperties: false,
  definitions: {
    "Record<string,Component>": {
      additionalProperties: false,
      // @ts-expect-error: typescript-json-schema generates the wrong JSON schema.
      type: "object",
    },
  },
  properties: {
    component: {
      $ref: "#/definitions/Record<string,Component>",
    },
  },
  required: ["component"],
  type: "object",
};

const validateSketch = new Ajv().compile(sketchSchema);

const initialSketch: Sketch = {
  component: {
    "df5bb750-e9fe-fbf3-26e0-bbd601fe98c9": {
      name: "sine",
      implementation: 10,
      outputDestinations: [
        { componentID: "5446b319-e7bc-4430-9773-1021cf7e2a7a", inputIndex: 1 },
      ],
      position: { x: 285, y: 36 },
      extendedData: {},
    },
    "d417eb39-d2d7-4023-a58f-f058658b7c40": {
      name: "speaker",
      outputDestinations: [],
      position: { x: 768, y: 112 },
      implementation: 18,
      extendedData: {},
    },
    "2979e003-3e55-4f18-a76e-097c94373540": {
      name: "keyboard frequency",
      outputDestinations: [
        { componentID: "df5bb750-e9fe-fbf3-26e0-bbd601fe98c9", inputIndex: 1 },
      ],
      position: { x: 38, y: 23 },
      implementation: 16,
      extendedData: {},
    },
    "c0f78421-49bb-49c1-a065-bd9fbabe65f1": {
      name: "keyboard switch",
      outputDestinations: [
        { componentID: "5446b319-e7bc-4430-9773-1021cf7e2a7a", inputIndex: 2 },
      ],
      position: { x: 280, y: 217 },
      implementation: 17,
      extendedData: {},
    },
    "5446b319-e7bc-4430-9773-1021cf7e2a7a": {
      name: "amplifier",
      outputDestinations: [
        { componentID: "d417eb39-d2d7-4023-a58f-f058658b7c40", inputIndex: 1 },
      ],
      position: { x: 524, y: 104 },
      implementation: 0,
      extendedData: {},
    },
  },
};

export { initialSketch, validateSketch };
export type { Sketch };
